// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMiWg-CoTOmdZ3wpint1gvdv4GqOrDxGk',
    appId: '1:417632057422:web:2e640f09fc4d65a387eb1f',
    messagingSenderId: '417632057422',
    projectId: 'dogclubdata-base',
    authDomain: 'dogclubdata-base.firebaseapp.com',
    storageBucket: 'dogclubdata-base.firebasestorage.app',
    measurementId: 'G-L3LSTPYQXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLHAG2CObJfU1UEvhPzBT2d1dBCmnRl0',
    appId: '1:417632057422:android:c74a12ff033f9ee087eb1f',
    messagingSenderId: '417632057422',
    projectId: 'dogclubdata-base',
    storageBucket: 'dogclubdata-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGXkiSHdmYwHV71j-i3jFNC8tIIxYs2I',
    appId: '1:417632057422:ios:0d6c2927c969155d87eb1f',
    messagingSenderId: '417632057422',
    projectId: 'dogclubdata-base',
    storageBucket: 'dogclubdata-base.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGXkiSHdmYwHV71j-i3jFNC8tIIxYs2I',
    appId: '1:417632057422:ios:0d6c2927c969155d87eb1f',
    messagingSenderId: '417632057422',
    projectId: 'dogclubdata-base',
    storageBucket: 'dogclubdata-base.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMiWg-CoTOmdZ3wpint1gvdv4GqOrDxGk',
    appId: '1:417632057422:web:534dac284904623787eb1f',
    messagingSenderId: '417632057422',
    projectId: 'dogclubdata-base',
    authDomain: 'dogclubdata-base.firebaseapp.com',
    storageBucket: 'dogclubdata-base.firebasestorage.app',
    measurementId: 'G-BS7C4GK4HN',
  );

}